2025-05-05 05:56:59,895 INFO    MainThread:984223 [wandb_setup.py:_flush():68] Current SDK version is 0.19.10
2025-05-05 05:56:59,895 INFO    MainThread:984223 [wandb_setup.py:_flush():68] Configure stats pid to 984223
2025-05-05 05:56:59,895 INFO    MainThread:984223 [wandb_setup.py:_flush():68] Loading settings from /home/rg3637/.config/wandb/settings
2025-05-05 05:56:59,898 INFO    MainThread:984223 [wandb_setup.py:_flush():68] Loading settings from /home/rg3637/hpml-assign2/hpml-project/wandb/settings
2025-05-05 05:56:59,899 INFO    MainThread:984223 [wandb_setup.py:_flush():68] Loading settings from environment variables
2025-05-05 05:56:59,899 INFO    MainThread:984223 [wandb_init.py:setup_run_log_directory():724] Logging user logs to /home/rg3637/hpml-assign2/hpml-project/wandb/run-20250505_055659-j2k3d4pe/logs/debug.log
2025-05-05 05:56:59,901 INFO    MainThread:984223 [wandb_init.py:setup_run_log_directory():725] Logging internal logs to /home/rg3637/hpml-assign2/hpml-project/wandb/run-20250505_055659-j2k3d4pe/logs/debug-internal.log
2025-05-05 05:56:59,901 INFO    MainThread:984223 [wandb_init.py:init():852] calling init triggers
2025-05-05 05:56:59,904 INFO    MainThread:984223 [wandb_init.py:init():857] wandb.init called with sweep_config: {}
config: {'model_name': 'google-bert/bert-base-cased', 'num_beams': 3, 'num_return_sequences': 3, 'max_length': 100, 'input_file': '/home/rg3637/hpml-assign2/hpml-project/because_mode.jsonl', '_wandb': {}}
2025-05-05 05:56:59,907 INFO    MainThread:984223 [wandb_init.py:init():893] starting backend
2025-05-05 05:56:59,910 INFO    MainThread:984223 [wandb_init.py:init():897] sending inform_init request
2025-05-05 05:56:59,956 INFO    MainThread:984223 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-05-05 05:56:59,957 INFO    MainThread:984223 [wandb_init.py:init():907] backend started and connected
2025-05-05 05:56:59,961 INFO    MainThread:984223 [wandb_init.py:init():1002] updated telemetry
2025-05-05 05:56:59,962 INFO    MainThread:984223 [wandb_init.py:init():1026] communicating run to backend with 90.0 second timeout
2025-05-05 05:57:00,376 INFO    MainThread:984223 [wandb_init.py:init():1101] starting run threads in backend
2025-05-05 05:57:00,641 WARNING MainThread:984223 [wandb_init.py:init():1654] [no run ID] interrupted
Traceback (most recent call last):
  File "/home/rg3637/anaconda3/envs/hpml/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1650, in init
    return wi.init(run_settings, run_config, run_printer)
  File "/home/rg3637/anaconda3/envs/hpml/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1146, in init
    run._on_start()
  File "/home/rg3637/anaconda3/envs/hpml/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2595, in _on_start
    self._backend.interface.publish_python_packages(working_set())
  File "/home/rg3637/anaconda3/envs/hpml/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 345, in publish_python_packages
    for pkg in working_set:
  File "/home/rg3637/anaconda3/envs/hpml/lib/python3.9/site-packages/wandb/util.py", line 1937, in working_set
    yield InstalledDistribution(key=d.metadata["Name"], version=d.version)
  File "/home/rg3637/anaconda3/envs/hpml/lib/python3.9/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 470, in version
    return self.metadata['Version']
  File "/home/rg3637/anaconda3/envs/hpml/lib/python3.9/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 455, in metadata
    return _adapters.Message(email.message_from_string(text))
  File "/home/rg3637/anaconda3/envs/hpml/lib/python3.9/email/__init__.py", line 38, in message_from_string
    return Parser(*args, **kws).parsestr(s)
  File "/home/rg3637/anaconda3/envs/hpml/lib/python3.9/email/parser.py", line 67, in parsestr
    return self.parse(StringIO(text), headersonly=headersonly)
  File "/home/rg3637/anaconda3/envs/hpml/lib/python3.9/email/parser.py", line 56, in parse
    feedparser.feed(data)
  File "/home/rg3637/anaconda3/envs/hpml/lib/python3.9/email/feedparser.py", line 176, in feed
    self._call_parse()
  File "/home/rg3637/anaconda3/envs/hpml/lib/python3.9/email/feedparser.py", line 180, in _call_parse
    self._parse()
  File "/home/rg3637/anaconda3/envs/hpml/lib/python3.9/email/feedparser.py", line 464, in _parsegen
    for line in self._input:
  File "/home/rg3637/anaconda3/envs/hpml/lib/python3.9/email/feedparser.py", line 129, in __next__
    line = self.readline()
  File "/home/rg3637/anaconda3/envs/hpml/lib/python3.9/email/feedparser.py", line 78, in readline
    def readline(self):
KeyboardInterrupt
2025-05-05 05:57:01,382 INFO    MsgRouterThr:984223 [mailbox.py:close():129] [no run ID] Closing mailbox, abandoning 0 handles.
